FROM rust:alpine AS builder
RUN apk add musl-dev
WORKDIR /app
COPY . .
RUN cargo build --release

FROM scratch
WORKDIR /app
RUN mkdir /tmp
COPY --from=builder /app/target/release/website .
CMD ["./website"]